=== unicode-org/cldr/LocaleElements.dtd
<!ELEMENT localeData ( identity, ( localeDisplayNames | layout | encodings | delimiters | measurement | dates | numbers | collations  | special*)* ) >
<!ATTLIST localeData
   version          CDATA              #FIXED "1.0"
>
<!-- ######################################################### -->

<!ELEMENT identity ( (version, generation, language, (territory? | variant? | script? | special*)*) | alias) >

<!ELEMENT version ( #PCDATA ) >
<!ATTLIST version number NMTOKEN #REQUIRED >

<!ELEMENT generation EMPTY >
<!ATTLIST generation date NMTOKEN #REQUIRED >

<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language type NMTOKEN #REQUIRED >

<!ELEMENT territory ( #PCDATA ) >
<!ATTLIST territory type NMTOKEN #REQUIRED >

<!ELEMENT variant ( #PCDATA ) >
<!ATTLIST variant type NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT localeDisplayNames ( ((scripts| languages| territories | variants  | keys | types | special*))* | alias ) >

<!ELEMENT scripts ( (script+ | special* )*   | alias ) >

<!ELEMENT script ( #PCDATA ) >
<!ATTLIST script type NMTOKEN #REQUIRED >

<!ELEMENT languages ( (language+ | special*)* | alias ) >

<!ELEMENT territories ( (territory+ | special*)* | alias ) >

<!ELEMENT variants ( (variant+ | special*)* | alias ) >

<!ELEMENT keys ( (key+ | special*) | alias ) >

<!ELEMENT key ( #PCDATA ) >
<!ATTLIST key type NMTOKEN #REQUIRED >

<!ELEMENT types ( (type+| special*)*| alias ) >

<!ELEMENT type ( #PCDATA ) >
<!ATTLIST type key NMTOKEN #REQUIRED >
<!ATTLIST type type NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT layout ( (orientation| special*)* | alias ) >

<!ELEMENT orientation EMPTY >
<!ATTLIST orientation characters NMTOKEN #REQUIRED >
<!ATTLIST orientation lines NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- ######################################################### -->
<!ELEMENT encodings ( (exemplarCharacters| mapping*| special*)*| alias ) >

<!ELEMENT exemplarCharacters ( #PCDATA ) >

<!ELEMENT mapping EMPTY >
<!ATTLIST mapping registry NMTOKEN #REQUIRED >
<!ATTLIST mapping type NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT delimiters ( (quotationStart| quotationEnd | alternateQuotationStart | alternateQuotationEnd | special*)* | alias ) >

<!ELEMENT quotationStart ( #PCDATA ) >

<!ELEMENT quotationEnd ( #PCDATA ) >

<!ELEMENT alternateQuotationStart ( #PCDATA ) >

<!ELEMENT alternateQuotationEnd ( #PCDATA ) >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT measurement ( (measurementSystem | paperSize | special*)* | alias ) >

<!ELEMENT paperSize ( (height | width | units | special* )* | alias ) >

<!ELEMENT height ( #PCDATA ) >

<!ELEMENT width ( #PCDATA ) >

<!ELEMENT units ( #PCDATA ) >


<!ELEMENT measurementSystem EMPTY >
<!ATTLIST measurementSystem type NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT dates ( (localizedPatternChars | calendars | timeZoneNames | special*)* | alias ) >

<!ELEMENT localizedPatternChars ( #PCDATA ) >

<!ELEMENT calendars ( (default | calendar+ | special*)* | alias ) >

<!ELEMENT calendar ( (am | dateFormats | dateTimeFormats | dayAbbr | dayNames | eras | monthAbbr | monthNames | pm | timeFormats | week | special*)* | alias) >
<!ATTLIST calendar type NMTOKEN #REQUIRED >

<!ELEMENT monthNames ( (month+ | special*)* | alias) >

<!ELEMENT month ( #PCDATA ) >
<!ATTLIST month type NMTOKEN #REQUIRED >

<!ELEMENT monthAbbr ( (month+ | special*)* | alias) >

<!ELEMENT dayNames ( (day+ | special*)* | alias ) >

<!ELEMENT day ( #PCDATA ) >
<!ATTLIST day type NMTOKEN #REQUIRED >

<!ELEMENT dayAbbr ( (day+ | special*)* | alias ) >

<!ELEMENT week ( (minDays | firstDay | weekendStart | weekendEnd | special* )* | alias ) >

<!ELEMENT minDays EMPTY >
<!ATTLIST minDays count NMTOKEN #REQUIRED >

<!ELEMENT firstDay EMPTY >
<!ATTLIST firstDay day NMTOKEN #REQUIRED >

<!ELEMENT weekendStart EMPTY >
<!ATTLIST weekendStart day NMTOKEN #REQUIRED >
<!ATTLIST weekendStart time NMTOKEN #REQUIRED >

<!ELEMENT weekendEnd EMPTY >
<!ATTLIST weekendEnd day NMTOKEN #REQUIRED >
<!ATTLIST weekendEnd time NMTOKEN #REQUIRED >

<!ELEMENT am ( #PCDATA ) >

<!ELEMENT pm ( #PCDATA ) >

<!ELEMENT eras ( (eraNames | eraAbbr | special*)* | alias ) >

<!ELEMENT eraNames ( (era+ | special*)* | alias ) >

<!ELEMENT eraAbbr ( (era+ | special*)* | alias ) >

<!ELEMENT era (#PCDATA) >
<!ATTLIST era type NMTOKEN #REQUIRED >

<!ELEMENT dateFormats ( (default | dateFormatLength+ | special*)* | alias ) >

<!ELEMENT dateFormatLength ( (default | dateFormat+ | special*)* | alias ) >
<!ATTLIST dateFormatLength type NMTOKEN #REQUIRED >

<!ELEMENT dateFormat ( (pattern | displayName | special*)* | alias ) >
<!ATTLIST dateFormat type NMTOKEN #IMPLIED >

<!ELEMENT displayName ( #PCDATA ) >

<!ELEMENT timeFormats ( (default | timeFormatLength+ | special*)* | alias ) >

<!ELEMENT timeFormatLength ( ( default | timeFormat | special* )* | alias) >
<!ATTLIST timeFormatLength type NMTOKEN #REQUIRED >

<!ELEMENT timeFormat ( (pattern | displayName | special*)* | alias ) >
<!ATTLIST timeFormat type NMTOKEN #IMPLIED >

<!ELEMENT dateTimeFormats ( (default | dateTimeFormatLength+ | special*)* | alias ) >

<!ELEMENT dateTimeFormatLength ( (default | dateTimeFormat+ | special*)* | alias ) >
<!ATTLIST dateTimeFormatLength type NMTOKEN #REQUIRED >

<!ELEMENT dateTimeFormat ( (pattern | displayName | special*)* | alias ) >
<!ATTLIST dateTimeFormat type NMTOKEN #IMPLIED >

<!ELEMENT timeZoneNames ( (default | zone+ | special*)* | alias ) >

<!ELEMENT zone ( (exemplarCity | long | short | special*)* | alias) >
<!ATTLIST zone type CDATA #REQUIRED >

<!ELEMENT long ( (generic | standard | daylight | special*)* | alias ) >

<!ELEMENT generic ( #PCDATA ) >

<!ELEMENT standard ( #PCDATA ) >

<!ELEMENT short ( (generic | standard | daylight | special*)* | alias) >

<!ELEMENT daylight ( #PCDATA ) >

<!ELEMENT exemplarCity ( #PCDATA ) >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT numbers ( (symbols | currencyFormats | decimalFormats | percentFormats | scientificFormats | currencies | special*)* | alias ) >

<!ELEMENT symbols ( (decimal | group | list | percentSign | nativeZeroDigit | patternDigit | plusSign | minusSign | exponential | perMille | infinity | nan | special*)* | alias ) >

<!ELEMENT decimal ( #PCDATA ) >

<!ELEMENT group ( #PCDATA ) >

<!ELEMENT list ( #PCDATA ) >

<!ELEMENT percentSign ( #PCDATA ) >

<!ELEMENT nativeZeroDigit ( #PCDATA ) >

<!ELEMENT patternDigit ( #PCDATA ) >

<!ELEMENT plusSign ( #PCDATA ) >

<!ELEMENT minusSign ( #PCDATA ) >

<!ELEMENT exponential ( #PCDATA ) >

<!ELEMENT perMille ( #PCDATA ) >

<!ELEMENT infinity ( #PCDATA ) >

<!ELEMENT nan ( #PCDATA ) >

<!ELEMENT pattern ( #PCDATA ) >
<!ATTLIST pattern type NMTOKEN #IMPLIED >

<!ELEMENT decimalFormats ( (default | decimalFormatLength+ | special*)* | alias) >
<!ELEMENT decimalFormatLength ( (default+ | decimalFormat+ | special*)* | alias ) >
<!ATTLIST decimalFormatLength type NMTOKEN #REQUIRED >
<!ELEMENT decimalFormat (pattern) >
<!ATTLIST decimalFormat type NMTOKEN #IMPLIED >

<!ELEMENT scientificFormats ( (default | scientificFormatLength+ | special*)* | alias) >
<!ELEMENT scientificFormatLength ( (default+ | scientificFormat+ | special*)* | alias ) >
<!ATTLIST scientificFormatLength type NMTOKEN #REQUIRED >
<!ELEMENT scientificFormat ((pattern | special*)* | alias) >
<!ATTLIST scientificFormat type NMTOKEN #IMPLIED >

<!ELEMENT percentFormats ( (default | percentFormatLength+ | special*)* | alias) >
<!ELEMENT percentFormatLength ( (default+ | percentFormat+ | special*)* | alias ) >
<!ATTLIST percentFormatLength type NMTOKEN #REQUIRED >
<!ELEMENT percentFormat ((pattern | special*)* | alias) >
<!ATTLIST percentFormat type NMTOKEN #IMPLIED >

<!ELEMENT currencyFormats ( (default | currencyFormatLength+ | special*)* | alias) >
<!ELEMENT currencyFormatLength ( (default+ | currencyFormat+ | special*)* | alias ) >
<!ATTLIST currencyFormatLength type NMTOKEN #REQUIRED >
<!ELEMENT currencyFormat ((pattern|  special*)* | alias) >
<!ATTLIST currencyFormat type NMTOKEN #IMPLIED >

<!ELEMENT currencies ( (default | currency+ | special*)* | alias ) >

<!ELEMENT currency ( (displayName | symbol | decimal? | group? | special*)* | alias ) >
<!ATTLIST currency id NMTOKEN #IMPLIED >
<!ATTLIST currency type NMTOKEN #IMPLIED >

<!ELEMENT symbol ( #PCDATA ) >

<!-- ######################################################### -->


<!-- ######################################################### -->

<!ELEMENT collations ( (default+ | collation+ | special*)* | alias ) >

<!ELEMENT collation ( ( special* | uca? | settings? | suppress_contractions? | optimize?   | rules? )* | alias ) >

<!ATTLIST collation type NMTOKEN #IMPLIED >

<!ELEMENT uca EMPTY >
<!ATTLIST uca version NMTOKEN #REQUIRED >

<!ELEMENT settings EMPTY >
<!ATTLIST settings caseLevel NMTOKEN #IMPLIED >
<!ATTLIST settings alternate NMTOKEN #IMPLIED >
<!ATTLIST settings backwards NMTOKEN #IMPLIED >
<!ATTLIST settings normalization NMTOKEN #IMPLIED >
<!ATTLIST settings caseFirst NMTOKEN #IMPLIED >
<!ATTLIST settings hiraganaQuarternary NMTOKEN #IMPLIED >
<!ATTLIST settings strength NMTOKEN #IMPLIED >
<!ATTLIST settings numeric NMTOKEN #IMPLIED >

<!ELEMENT suppress_contractions (  #PCDATA ) >

<!ELEMENT optimize ( #PCDATA ) >

<!ELEMENT rules ( (special* | p | pc | position | reset | s | sc | t | tc | q | qc | i | ic)* | alias) >

<!ELEMENT p ( #PCDATA | context | cp)* >

<!ELEMENT pc ( #PCDATA | context | cp )* >

<!ELEMENT s ( #PCDATA | context | cp )* >

<!ELEMENT sc ( #PCDATA | context | cp )* >

<!ELEMENT t ( #PCDATA | context | cp )* >

<!ELEMENT tc ( #PCDATA | context | cp )* >

<!ELEMENT q ( #PCDATA | context | cp )* >

<!ELEMENT qc ( #PCDATA | context | cp )* >

<!ELEMENT i ( #PCDATA | context | cp )* >

<!ELEMENT ic ( #PCDATA | context | cp )* >

<!ELEMENT reset ( #PCDATA | context | cp | top )* >
<!ATTLIST reset before NMTOKEN #IMPLIED >

<!ELEMENT top EMPTY >

<!ELEMENT context (  #PCDATA ) >

<!ELEMENT position EMPTY >
<!ATTLIST position at CDATA #REQUIRED >

<!ELEMENT cp EMPTY >
<!ATTLIST cp hex NMTOKEN #REQUIRED >

<!-- ######################################################### -->


<!-- These elements are common to all elements defined above -->
<!-- ######################################################### -->

<!ELEMENT alias EMPTY >
<!ATTLIST alias source NMTOKEN #REQUIRED >
<!ATTLIST alias type NMTOKEN #REQUIRED >

<!ELEMENT default EMPTY >
<!ATTLIST default type CDATA #REQUIRED >

<!ELEMENT special ANY >
<!ATTLIST special formatindex NMTOKEN #IMPLIED >
<!ATTLIST special msgtype NMTOKEN #IMPLIED >
<!ATTLIST special owner CDATA #REQUIRED >
<!ATTLIST special usage NMTOKEN #IMPLIED >
<!ATTLIST special version NMTOKEN #IMPLIED >
<!ATTLIST special default NMTOKEN #IMPLIED>
<!ATTLIST special type NMTOKEN #IMPLIED>
<!ATTLIST special unoid NMTOKEN #IMPLIED>

<!-- ######################################################### -->


<!--  ICU Specific elements                                    -->
<!-- ######################################################### -->

<!-- RBNF data -->
<!ELEMENT ruleBasedNumberFormat (#PCDATA | cp)* >
<!ATTLIST ruleBasedNumberFormat type NMTOKEN #REQUIRED >

<!ELEMENT ruleBasedNumberFormats ( ruleBasedNumberFormat+ | alias ) >

<!-- RBBI data -->
<!ELEMENT boundaries ( (grapheme? | word? | line? | sentence? | special*)* | alias ) >
<!ELEMENT grapheme ( #PCDATA ) >
<!ATTLIST grapheme class NMTOKEN #REQUIRED >
<!ATTLIST grapheme append NMTOKEN #REQUIRED >

<!ELEMENT word ( #PCDATA ) >
<!ATTLIST word class NMTOKEN #REQUIRED >
<!ATTLIST word import NMTOKEN #REQUIRED >

<!ELEMENT line ( #PCDATA ) >
<!ATTLIST line class NMTOKEN #REQUIRED >


<!ELEMENT sentence ( #PCDATA ) >
<!ATTLIST sentence class NMTOKEN #REQUIRED >

<!-- RBT data  -->
<!ELEMENT transforms ( (transform | special*)* | alias ) >
<!ELEMENT transform ( #PCDATA ) >
<!ATTLIST transform type NMTOKEN #REQUIRED >

<!-- ######################################################### -->



<!--  OpenOffice.org Specific elements                         -->
<!-- ######################################################### -->

<!ELEMENT numberingLevels ( (numberingLevel+ | special*)* | alias ) >

<!ELEMENT numberingLevel EMPTY >
<!ATTLIST numberingLevel numType NMTOKEN #REQUIRED >
<!ATTLIST numberingLevel prefix CDATA #REQUIRED >
<!ATTLIST numberingLevel suffix CDATA #REQUIRED >

<!ELEMENT reservedWords ( (trueWord | falseWord | quarter1Word | quarter2Word | quarter3Word | quarter4Word | aboveWord | belowWord | special*)* | alias ) >

<!ELEMENT trueWord ( #PCDATA ) >

<!ELEMENT falseWord ( #PCDATA ) >

<!ELEMENT quarter1Word ( #PCDATA ) >

<!ELEMENT quarter2Word ( #PCDATA ) >

<!ELEMENT quarter3Word ( #PCDATA ) >

<!ELEMENT quarter4Word ( #PCDATA ) >

<!ELEMENT aboveWord ( #PCDATA ) >

<!ELEMENT belowWord ( #PCDATA ) >

<!ELEMENT transliterationModules ( #PCDATA ) >

<!ELEMENT outLineNumberingLevel EMPTY >

<!ELEMENT collator EMPTY >
<!ATTLIST collator type NMTOKEN #REQUIRED >

<!-- ######################################################### -->



<!--  POSIX/XPG4 Specific elements                             -->
<!-- ######################################################### -->

<!ELEMENT messages ( (no | yes | shortYes | shortNo | special*)* | alias ) >

<!ELEMENT yes ( #PCDATA ) >

<!ELEMENT shortYes ( #PCDATA ) >

<!ELEMENT no ( #PCDATA ) >

<!ELEMENT shortNo ( #PCDATA ) >

<!ELEMENT include ( #PCDATA ) >

<!-- ######################################################### -->


<!--  TR-14652/GLIBC Specific elements                         -->
<!-- ######################################################### -->

<!ELEMENT addressFormat ( (postalPattern | special*)* | alias ) >

<!ELEMENT postalPattern ( #PCDATA ) >

<!ELEMENT nameFormat ( (namePattern | generalSalutation | shortSalutationMr | shortSalutationMiss | shortSalutationMrs | longSalutationMr | longSalutationMiss | longSalutationMrs | special*)* | alias ) >

<!ELEMENT namePattern ( #PCDATA ) >

<!ELEMENT generalSalutation ( #PCDATA ) >

<!ELEMENT shortSalutationMiss ( #PCDATA ) >

<!ELEMENT shortSalutationMr ( #PCDATA ) >

<!ELEMENT shortSalutationMrs ( #PCDATA ) >

<!ELEMENT longSalutationMiss ( #PCDATA ) >

<!ELEMENT longSalutationMr ( #PCDATA ) >

<!ELEMENT longSalutationMrs ( #PCDATA ) >

<!ELEMENT identification ( (title | source | address | contact | email | telephone | fax | languageUsed | country | audience | application | abbreviation | revision | date | special*)* | alias ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT source ( #PCDATA ) >

<!ELEMENT address ( #PCDATA ) >

<!ELEMENT contact ( #PCDATA ) >

<!ELEMENT email ( #PCDATA ) >

<!ELEMENT telephone ( #PCDATA ) >

<!ELEMENT fax ( #PCDATA ) >

<!ELEMENT languageUsed ( #PCDATA ) >

<!ELEMENT country ( #PCDATA ) >

<!ELEMENT audience ( #PCDATA ) >

<!ELEMENT application ( #PCDATA ) >

<!ELEMENT abbreviation ( #PCDATA ) >

<!ELEMENT revision ( #PCDATA ) >

<!ELEMENT date ( #PCDATA ) >

<!ELEMENT telephoneFormat ( (internationalPattern | domesticPattern | internationalDialCode | internationalPrefix | special*)* | alias ) >

<!ELEMENT internationalPattern ( #PCDATA ) >

<!ELEMENT domesticPattern ( #PCDATA ) >

<!ELEMENT internationalDialCode ( #PCDATA ) >

<!ELEMENT internationalPrefix ( #PCDATA ) >

<!ELEMENT countryInfo ( (countryPost | countryCar | countryNumber | countryISBNNumber | special*)* | alias ) >

<!ELEMENT countryPost ( #PCDATA ) >

<!ELEMENT countryCar ( #PCDATA ) >

<!ELEMENT countryNumber EMPTY >
<!ATTLIST countryNumber type NMTOKEN #REQUIRED >

<!ELEMENT countryISBNNumber EMPTY >
<!ATTLIST countryISBNNumber type NMTOKEN #REQUIRED >

<!-- ######################################################### -->

=== unicode-org/cldr/external/ibmjdk/main/hr.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE localeData SYSTEM "http://oss.software.ibm.com/cvs/icu/~checkout~/locale/LocaleElements.dtd" >
<localeData>
	<identity>
		<version number="1.0">Various notes and changes in version 1.0</version>
		<generation date="2003-01-10" />
		<language type="hr"></language>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="hr">hrvatski</language>
		</languages>
		<territories>
			<territory type="HR">Hrvatska</territory>
		</territories>
		<keys>
			<key type="collation">collation</key>
			<key type="calendar">calendar</key>
		</keys>
	</localeDisplayNames>
	<layout>
		<orientation lines="top-to-bottom" characters="left-to-right" />
	</layout>
		<dates>
			<localizedPatternChars>GanjkHmsSEDFwWxhKzZ</localizedPatternChars>
			<calendars>
				<default type="gregorian"/>
				<calendar type="gregorian">
					<monthNames>
						<month type="1">siječanj</month>
						<month type="2">veljača</month>
						<month type="3">ožujak</month>
						<month type="4">travanj</month>
						<month type="5">svibanj</month>
						<month type="6">lipanj</month>
						<month type="7">srpanj</month>
						<month type="8">kolovoz</month>
						<month type="9">rujan</month>
						<month type="10">listopad</month>
						<month type="11">studeni</month>
						<month type="12">prosinac</month>
						<month type="13"></month>
					</monthNames>
					<monthAbbr>
						<month type="1">sij</month>
						<month type="2">vel</month>
						<month type="3">ožu</month>
						<month type="4">tra</month>
						<month type="5">svi</month>
						<month type="6">lip</month>
						<month type="7">srp</month>
						<month type="8">kol</month>
						<month type="9">ruj</month>
						<month type="10">lis</month>
						<month type="11">stu</month>
						<month type="12">pro</month>
						<month type="13"></month>
					</monthAbbr>
					<dayNames>
						<day type="sun">nedjelja</day>
						<day type="mon">ponedjeljak</day>
						<day type="tue">utorak</day>
						<day type="wed">srijeda</day>
						<day type="thu">četvrtak</day>
						<day type="fri">petak</day>
						<day type="sat">subota</day>
					</dayNames>
					<dayAbbr>
						<day type="sun">ned</day>
						<day type="mon">pon</day>
						<day type="tue">uto</day>
						<day type="wed">sri</day>
						<day type="thu">čet</day>
						<day type="fri">pet</day>
						<day type="sat">sub</day>
					</dayAbbr>
					<dateFormats>
						<default type="medium"/>
						<dateFormat type="full">
							<pattern>yyyy. MMMM dd</pattern>
						</dateFormat>
						<dateFormat type="long">
							<pattern>yyyy. MMMM dd</pattern>
						</dateFormat>
						<dateFormat type="medium">
							<pattern>yyyy.MM.dd</pattern>
						</dateFormat>
						<dateFormat type="short">
							<pattern>yyyy.MM.dd</pattern>
						</dateFormat>
					</dateFormats>
					<timeFormats>
						<default type="medium"/>
						<timeFormat type="full">
							<pattern>HH:mm:ss z</pattern>
						</timeFormat>
						<timeFormat type="long">
							<pattern>HH:mm:ss z</pattern>
						</timeFormat>
						<timeFormat type="medium">
							<pattern>HH:mm:ss</pattern>
						</timeFormat>
						<timeFormat type="short">
							<pattern>HH:mm</pattern>
						</timeFormat>
					</timeFormats>
					<dateTimeFormat>
						<pattern>{1} {0}</pattern>
					</dateTimeFormat>
				</calendar>
			</calendars>
		</dates>
			<collations>
				<collation  >
					<rules>
						<reset></reset>
						<i>̌</i>
						<reset>̆</reset>
						<i>̍</i>
						<reset>C</reset>
						<p>č</p>
						<t>Č</t>
						<p>ć</p>
						<t>Ć</t>
						<reset>D</reset>
						<p>ǳ</p>
						<tc>ǲǱ</tc>
						<p>dz</p>
						<tc>dZDzDZ</tc>
						<p>ǆ</p>
						<tc>ǅǄ</tc>
						<p>đ</p>
						<t>Đ</t>
						<reset>L</reset>
						<p>lj</p>
						<tc>lJLjLJ</tc>
						<reset>N</reset>
						<p>nj</p>
						<tc>nJNjNJ</tc>
						<reset>S</reset>
						<p>š</p>
						<t>Š</t>
						<reset>Z</reset>
						<p>ž</p>
					</rules>
					<special owner="http://oss.software.ibm.com/icu/" version="1.0" />
				</collation  >
			</collations>
</localeData>
