<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messagebundle [
<!ELEMENT messagebundle (msg)*>
<!ATTLIST messagebundle class CDATA #IMPLIED>

<!ELEMENT msg (#PCDATA|ph|source)*>
<!ATTLIST msg id CDATA #IMPLIED>
<!ATTLIST msg seq CDATA #IMPLIED>
<!ATTLIST msg name CDATA #IMPLIED>
<!ATTLIST msg desc CDATA #IMPLIED>
<!ATTLIST msg meaning CDATA #IMPLIED>
<!ATTLIST msg obsolete (obsolete) #IMPLIED>
<!ATTLIST msg xml:space (default|preserve) "default">
<!ATTLIST msg is_hidden CDATA #IMPLIED>

<!ELEMENT source (#PCDATA)>

<!ELEMENT ph (#PCDATA|ex)*>
<!ATTLIST ph name CDATA #REQUIRED>

<!ELEMENT ex (#PCDATA)>
]>
<!-- English -->
<messagebundle class='CLDR'> <!-- 2011-03-01T17:05:04Z -->

	<!-- //ldml/characters/ellipsis[@type="final"] -->
	<msg id='8185172660664561036'
		desc='Supply the elipsis pattern for when the final part of a string is omitted. Note: before translating, be sure to read http://cldr.org/translation/characters.'>
		<ph name='FIRST_PART_OF_TEXT'>
			<ex>very long na</ex>
			{0}
		</ph>
		…
	</msg>
	<!-- English original: {0}… -->

	<!-- //ldml/characters/ellipsis[@type="initial"] -->
	<msg id='4862514304103369633'
		desc='Supply the elipsis pattern for when the initial part of a string is omitted. Note: before translating, be sure to read http://cldr.org/translation/characters.'>
		…
		<ph name='LAST_PART_OF_TEXT'>
			<ex>ry long name</ex>
			{0}
		</ph>
	</msg>
	<!-- English original: …{0} -->

	<!-- //ldml/characters/ellipsis[@type="medial"] -->
	<msg id='6271151634807937467'
		desc='Supply the elipsis pattern for when the medial part of a string is omitted. Note: before translating, be sure to read http://cldr.org/translation/characters.'>
		<ph name='FIRST_PART_OF_TEXT'>
			<ex>very l</ex>
			{0}
		</ph>
		…
		<ph name='LAST_PART_OF_TEXT'>
			<ex>g name</ex>
			{1}
		</ph>
	</msg>
	<!-- English original: {0}…{1} -->

	<!-- //ldml/characters/exemplarCharacters -->
	<msg id='9140199787568256493'
		desc='Supply the characters used in your language for the "standard" category. Note: before translating, be sure to read http://cldr.org/translation/exemplars.'>[a
		b c d e f g h i j k l m n o p q r s t u v w x y z]</msg>

	<!-- //ldml/characters/exemplarCharacters[@type="auxiliary"] -->
	<msg id='2811347674030337850'
		desc='Supply the characters used in your language for the "auxiliary" category.  Note: before translating, be sure to read http://cldr.org/translation/exemplars.'>[á
		à ă â å ä ã ā æ ç é è ĕ ê ë ē í ì ĭ î ï ī ñ ó ò ŏ ô ö ø ō œ ú ù ŭ û ü
		ū ÿ]</msg>

	<!-- //ldml/characters/exemplarCharacters[@type="currencySymbol"] -->
	<msg id='684343635911473473'
		desc='Supply the characters used in your language for the "currencySymbol" category.  Note: before translating, be sure to read http://cldr.org/translation/exemplars.'>[a
		b c č d e f g h i j k l ł m n o º p q r s t u v w x y z]</msg>

	<!-- //ldml/characters/exemplarCharacters[@type="index"] -->
	<msg id='7205786997640825427'
		desc='Supply the characters used in your language for the "index" category.  Note: before translating, be sure to read http://cldr.org/translation/exemplars.'>[A
		B C D E F G H I J K L M N O P Q R S T U V W X Y Z]</msg>

	<!-- //ldml/characters/exemplarCharacters[@type="punctuation"] -->
	<msg id='7852382081805980792'
		desc='Supply the characters used in your language for the "punctuation" category.  Note: before translating, be sure to read http://cldr.org/translation/exemplars.'>[\-
		‐ – — , ; : ! ? . … ‘ ' ’ ′ ″ “ &quot; ” ( ) [ ] / @ \&amp; # § † ‡ *]</msg>

	<!-- //ldml/characters/moreInformation -->
	<msg id='421611067904725230'
		desc='The character or short string used to indicate that more information is available. Note: before translating, be sure to read http://cldr.org/translation/characters.'>?</msg>

	<!-- //ldml/characters/stopwords/stopwordList[@type="collation"] -->
	<msg id='7682287553033526689'
		desc='The words that should be ignored in sorting in your language.  For more information, see http://cldr.org/translation/misc.'>a
		an the</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateFormats/dateFormatLength[@type="full"]/dateFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='6210350382081827617'
		desc='Provide the full version of the basic date pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>EEEE,
		MMMM d, y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateFormats/dateFormatLength[@type="long"]/dateFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='6732504890397537339'
		desc='Provide the long version of the basic date pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>MMMM
		d, y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateFormats/dateFormatLength[@type="medium"]/dateFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='1447427380805567966'
		desc='Provide the medium version of the basic date pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>MMM
		d, y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateFormats/dateFormatLength[@type="short"]/dateFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='6330584233113555553'
		desc='Provide the short version of the basic date pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>M/d/yy</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="EEEd"] -->
	<msg id='2529165261377354628'
		desc='Provide the pattern used in your language for the skeleton "EEEd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>d
		EEE</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="H"] -->
	<msg id='4001057923010278347'
		desc='Provide the pattern used in your language for the skeleton "H". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>HH</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="Hm"] -->
	<msg id='4151110772708638059'
		desc='Provide the pattern used in your language for the skeleton "Hm". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>HH:mm</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="Hms"] -->
	<msg id='2854320925378519795'
		desc='Provide the pattern used in your language for the skeleton "Hms". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>HH:mm:ss</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="M"] -->
	<msg id='673793593956275759'
		desc='Provide the pattern used in your language for the skeleton "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>L</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="MEd"] -->
	<msg id='3247726803356129266'
		desc='Provide the pattern used in your language for the skeleton "MEd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>E,
		M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="MMM"] -->
	<msg id='1013768162887057512'
		desc='Provide the pattern used in your language for the skeleton "MMM". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>LLL</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="MMMEd"] -->
	<msg id='9186177300426181649'
		desc='Provide the pattern used in your language for the skeleton "MMMEd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>E,
		MMM d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="MMMd"] -->
	<msg id='221321083177551305'
		desc='Provide the pattern used in your language for the skeleton "MMMd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>MMM
		d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="Md"] -->
	<msg id='6538040223709988217'
		desc='Provide the pattern used in your language for the skeleton "Md". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="d"] -->
	<msg id='8557845258546098365'
		desc='Provide the pattern used in your language for the skeleton "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="h"] -->
	<msg id='8679350314963209201'
		desc='Provide the pattern used in your language for the skeleton "h". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>h
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="hm"] -->
	<msg id='4773242185769283699'
		desc='Provide the pattern used in your language for the skeleton "hm". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>h:mm
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="hms"] -->
	<msg id='7843817634035465858'
		desc='Provide the pattern used in your language for the skeleton "hms". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>h:mm:ss
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="ms"] -->
	<msg id='459920444600419621'
		desc='Provide the pattern used in your language for the skeleton "ms". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>mm:ss</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="y"] -->
	<msg id='1904668687439282446'
		desc='Provide the pattern used in your language for the skeleton "y". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yM"] -->
	<msg id='1954174190818570532'
		desc='Provide the pattern used in your language for the skeleton "yM". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>M/y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yMEd"] -->
	<msg id='7592896315352840199'
		desc='Provide the pattern used in your language for the skeleton "yMEd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>EEE,
		M/d/y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yMMM"] -->
	<msg id='8064333019529688760'
		desc='Provide the pattern used in your language for the skeleton "yMMM". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>MMM
		y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yMMMEd"] -->
	<msg id='9179429504910909742'
		desc='Provide the pattern used in your language for the skeleton "yMMMEd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>EEE,
		MMM d, y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yMMMd"] -->
	<msg id='5987369100060187529'
		desc='Provide the pattern used in your language for the skeleton "yMMMd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>MMM
		d, y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yMd"] -->
	<msg id='5400248832742034911'
		desc='Provide the pattern used in your language for the skeleton "yMd". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>M/d/y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yQ"] -->
	<msg id='5058436088194874143'
		desc='Provide the pattern used in your language for the skeleton "yQ". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>Q
		y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="yQQQ"] -->
	<msg id='6001295352976118387'
		desc='Provide the pattern used in your language for the skeleton "yQQQ". Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>QQQ
		y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/dateTimeFormatLength[@type="full"]/dateTimeFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='345353161840063720'
		desc='Provide the full version of the date-time pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>
		<ph name='DATE'>
			<ex>Dec 10, 2010</ex>
			{1}
		</ph>
		<ph name='TIME'>
			<ex>3:59</ex>
			{0}
		</ph>
	</msg>
	<!-- English original: {1} {0} -->

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/dateTimeFormatLength[@type="long"]/dateTimeFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='81519248169835085'
		desc='Provide the long version of the date-time pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>
		<ph name='DATE'>
			<ex>Dec 10, 2010</ex>
			{1}
		</ph>
		<ph name='TIME'>
			<ex>3:59</ex>
			{0}
		</ph>
	</msg>
	<!-- English original: {1} {0} -->

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/dateTimeFormatLength[@type="medium"]/dateTimeFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='8806325220916789543'
		desc='Provide the medium version of the date-time pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>
		<ph name='DATE'>
			<ex>Dec 10, 2010</ex>
			{1}
		</ph>
		<ph name='TIME'>
			<ex>3:59</ex>
			{0}
		</ph>
	</msg>
	<!-- English original: {1} {0} -->

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/dateTimeFormatLength[@type="short"]/dateTimeFormat[@type="standard"]/pattern[@type="standard"] -->
	<msg id='1243485341831938657'
		desc='Provide the short version of the date-time pattern. Note: before translating, be sure to read http://cldr.org/translation/date-time-patterns.'>
		<ph name='DATE'>
			<ex>Dec 10, 2010</ex>
			{1}
		</ph>
		<ph name='TIME'>
			<ex>3:59</ex>
			{0}
		</ph>
	</msg>
	<!-- English original: {1} {0} -->

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatFallback -->
	<msg id='7941881824230976478'
		desc='The pattern used for "fallback" with date/time intervals. Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>
		<ph name='START_DATE_OR_TIME'>
			<ex>Nov 10</ex>
			{0}
		</ph>
		–
		<ph name='END_DATE_OR_TIME'>
			<ex>Dec 10</ex>
			{1}
		</ph>
	</msg>
	<!-- English original: {0} – {1} -->

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="H"]/greatestDifference[@id="H"] -->
	<msg id='8226759644531048511'
		desc='The pattern used for the date/time interval skeleton "H" when the greatest difference is "H". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH–HH</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="H"]/greatestDifference[@id="a"] -->
	<msg id='8190100716823312848'
		desc='The pattern used for the date/time interval skeleton "H" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH–HH</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hm"]/greatestDifference[@id="H"] -->
	<msg id='5523312428350772189'
		desc='The pattern used for the date/time interval skeleton "Hm" when the greatest difference is "H". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hm"]/greatestDifference[@id="a"] -->
	<msg id='3425099128802944302'
		desc='The pattern used for the date/time interval skeleton "Hm" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hm"]/greatestDifference[@id="m"] -->
	<msg id='6905520558889120030'
		desc='The pattern used for the date/time interval skeleton "Hm" when the greatest difference is "m". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hmv"]/greatestDifference[@id="H"] -->
	<msg id='4534830485308994256'
		desc='The pattern used for the date/time interval skeleton "Hmv" when the greatest difference is "H". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm
		v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hmv"]/greatestDifference[@id="a"] -->
	<msg id='3990577394903447322'
		desc='The pattern used for the date/time interval skeleton "Hmv" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm
		v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hmv"]/greatestDifference[@id="m"] -->
	<msg id='4164370099861076374'
		desc='The pattern used for the date/time interval skeleton "Hmv" when the greatest difference is "m". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH:mm–HH:mm
		v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hv"]/greatestDifference[@id="H"] -->
	<msg id='7257953848295141003'
		desc='The pattern used for the date/time interval skeleton "Hv" when the greatest difference is "H". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH–HH
		v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Hv"]/greatestDifference[@id="a"] -->
	<msg id='5638873634803457715'
		desc='The pattern used for the date/time interval skeleton "Hv" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>HH–HH
		v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="M"]/greatestDifference[@id="M"] -->
	<msg id='6729053935477713243'
		desc='The pattern used for the date/time interval skeleton "M" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>M–M</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MEd"]/greatestDifference[@id="M"] -->
	<msg id='7526182999354469817'
		desc='The pattern used for the date/time interval skeleton "MEd" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>E,
		M/d – E, M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MEd"]/greatestDifference[@id="d"] -->
	<msg id='1731720509380344511'
		desc='The pattern used for the date/time interval skeleton "MEd" when the greatest difference is "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>E,
		M/d – E, M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MMM"]/greatestDifference[@id="M"] -->
	<msg id='2778619793343455572'
		desc='The pattern used for the date/time interval skeleton "MMM" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>MMM–MMM</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MMMEd"]/greatestDifference[@id="M"] -->
	<msg id='47497705236295273'
		desc='The pattern used for the date/time interval skeleton "MMMEd" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>E,
		MMM d – E, MMM d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MMMEd"]/greatestDifference[@id="d"] -->
	<msg id='7035773951901417047'
		desc='The pattern used for the date/time interval skeleton "MMMEd" when the greatest difference is "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>E,
		MMM d – E, MMM d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MMMd"]/greatestDifference[@id="M"] -->
	<msg id='1873849101000351808'
		desc='The pattern used for the date/time interval skeleton "MMMd" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>MMM
		d – MMM d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="MMMd"]/greatestDifference[@id="d"] -->
	<msg id='3077085102806850482'
		desc='The pattern used for the date/time interval skeleton "MMMd" when the greatest difference is "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>MMM
		d–d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Md"]/greatestDifference[@id="M"] -->
	<msg id='5746913512507971763'
		desc='The pattern used for the date/time interval skeleton "Md" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>M/d
		– M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="Md"]/greatestDifference[@id="d"] -->
	<msg id='331592232836796987'
		desc='The pattern used for the date/time interval skeleton "Md" when the greatest difference is "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>M/d
		– M/d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="d"]/greatestDifference[@id="d"] -->
	<msg id='2538393037643417038'
		desc='The pattern used for the date/time interval skeleton "d" when the greatest difference is "d". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>d–d</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="h"]/greatestDifference[@id="a"] -->
	<msg id='5721456602226051372'
		desc='The pattern used for the date/time interval skeleton "h" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h
		a – h a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="h"]/greatestDifference[@id="h"] -->
	<msg id='9185519074943851240'
		desc='The pattern used for the date/time interval skeleton "h" when the greatest difference is "h". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h–h
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hm"]/greatestDifference[@id="a"] -->
	<msg id='8497942894859464681'
		desc='The pattern used for the date/time interval skeleton "hm" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm
		a – h:mm a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hm"]/greatestDifference[@id="h"] -->
	<msg id='9105164770007123739'
		desc='The pattern used for the date/time interval skeleton "hm" when the greatest difference is "h". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm–h:mm
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hm"]/greatestDifference[@id="m"] -->
	<msg id='5784417778574165775'
		desc='The pattern used for the date/time interval skeleton "hm" when the greatest difference is "m". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm–h:mm
		a</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hmv"]/greatestDifference[@id="a"] -->
	<msg id='7870133274672603237'
		desc='The pattern used for the date/time interval skeleton "hmv" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm
		a – h:mm a v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hmv"]/greatestDifference[@id="h"] -->
	<msg id='7690751392052311723'
		desc='The pattern used for the date/time interval skeleton "hmv" when the greatest difference is "h". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm–h:mm
		a v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hmv"]/greatestDifference[@id="m"] -->
	<msg id='7836477155486787849'
		desc='The pattern used for the date/time interval skeleton "hmv" when the greatest difference is "m". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h:mm–h:mm
		a v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hv"]/greatestDifference[@id="a"] -->
	<msg id='5586095693337638425'
		desc='The pattern used for the date/time interval skeleton "hv" when the greatest difference is "a". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h
		a – h a v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="hv"]/greatestDifference[@id="h"] -->
	<msg id='3954107021645421790'
		desc='The pattern used for the date/time interval skeleton "hv" when the greatest difference is "h". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>h–h
		a v</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="y"]/greatestDifference[@id="y"] -->
	<msg id='7220378199266486682'
		desc='The pattern used for the date/time interval skeleton "y" when the greatest difference is "y". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>y–y</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="yM"]/greatestDifference[@id="M"] -->
	<msg id='4354713533892381025'
		desc='The pattern used for the date/time interval skeleton "yM" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>M/yy
		– M/yy</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="yM"]/greatestDifference[@id="y"] -->
	<msg id='8816954728402339852'
		desc='The pattern used for the date/time interval skeleton "yM" when the greatest difference is "y". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>M/yy
		– M/yy</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="yMEd"]/greatestDifference[@id="M"] -->
	<msg id='9113253010456902905'
		desc='The pattern used for the date/time interval skeleton "yMEd" when the greatest difference is "M". Note: before translating, be sure to read http://cldr.org/translation/date-time-intervals.'>E,
		M/d/yy – E, M/d/yy</msg>

	<!-- //ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/intervalFormats/intervalFormatItem[@id="yMEd"]/greatestDifference[@id="d"] -->
	<msg id='1529612823641510100'